### ISSUE TITLE
Add a way to run the benchmark code with only one version of Underscore

### ISSUE THREAD

**Issue by jgonggrijp** [offen/underscore-benchmark#2]
When testers find a significant difference, it is nice if they can profile the benchmark code, first with the baseline version and then with the comparison version, in order to determine which Underscore functions have slowed down (or sped up) most. For this to produce useful numbers, it is important that the benchmark runs with only one version at a time; otherwise, the profiler is likely to just average the results.

**Comment by jgonggrijp** [comment]
Yes that sounds sensible. Not sure how to port that to the browser, though. Maybe a query parameter?

**Comment by m90** [comment]
Oh yeah, the browser makes it a little more tricky. Using a query parameter should work I think.
